spring:
  profiles:
    group:
      demo: h2db, demo-data
    active: default
  devtools:
    add-properties: false
server:
  port: 8080
logging:
  level:
    root: WARN
    org.springframework: INFO

# Actuator Endpoints
management:
  endpoint:
    health:
      probes:
        enabled: true #  "liveness" and "readiness" (set by K8s?)
  endpoints:
    web:
      exposure:
        include: health,info,loggers

---

spring:
  config:
    activate:
      on-profile: debug-log
  devtools:
    add-properties: on
logging:
  level:
    root: WARN
    org.springframework: INFO
    org.springframework.web.filter: DEBUG # Logging incoming requests see RequestLoggingFilterConfig
    de.cyclingsir.cetrack: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

---

spring:
  config:
    activate:
      on-profile: local
  servlet:
    multipart:
      max-file-size: 512KB
      max-request-size: 512KB
  flyway:
    enabled: true
    baseline-version: 0.1
    baseline-on-migrate: true
    locations: classpath:db/migration/mysql
  security:
    user:
      name: user
      password: pwd
# open more actuator endpoints for local testing
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,loggers,prometheus

---

spring:
  config:
    activate:
      on-profile: mysql
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:ceparts}?useSSL=${MYSQL_USE_SSL:true}&requireSSL=${MYSQL_REQUIRE_SSL:false}&verifyServerCertificate=${MYSQL_VERIFY_SERVER_CERTIFICATE:false}&useServerPrepStmts=true&useTimezone=true&useLegacyDatetimeCode=false&serverTimezone=UTC&sendFractionalSeconds=true
    username: ${MYSQL_USER:parts}
    password: ${MYSQL_PASSWORD:parts}
    hikari:
      pool-name: ${spring.application.name}
      data-source-properties:
        useUnicode: true
        characterEncoding: UTF-8
  jpa:
    hibernate:
      ddl-auto: ${hibernate.ddl:validate}
    properties:
      hibernate:
        dialect: ${MYSQL_DIALECT:org.hibernate.dialect.MySQLDialect}
  flyway:
    enabled: true
    baseline-version: 0.1
    baseline-on-migrate: true
    locations: classpath:db/migration/mysql
  h2:
    console:
      enabled: false
  sql:
    init:
      platform: mysql

---

spring:
  config:
    activate:
      on-profile: h2db
  jpa:
    database: h2
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    properties:
      hibernate:
#        format_sql: true
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_ON_EXIT=false
#    url: jdbc:h2:tcp//localhost:9092/./testDB2;DB_CLOSE_ON_EXIT=false
    username: sa
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: "/h2"
      settings:
        web-allow-others: true
        trace: true
  sql:
    init:
      mode: always
      platform: h2
  flyway:
    enabled: false

---

spring:
  config:
    activate:
      on-profile: demo-data
  sql:
    init:
      mode: always
      platform: demo
