-- DDL for MyTourbook Derby DB test fixture.
-- Source: dblook output from real DB (anonymized copy), Derby 10.16.1.1.
-- Tables: USER.TOURDATA, USER.TOURTAG, USER.TOURDATA_TOURTAG, USER.DBVERSION.
--
-- Fixture deviations from the real schema (documented here for CE-0036):
--   1. TOURTAG.TAGID: changed from GENERATED ALWAYS AS IDENTITY to plain BIGINT PK,
--      so data.sql can insert explicit tag IDs.
--   2. TOURDATA.SERIEDATA: changed from NOT NULL to nullable (saves GPS BLOB tracks;
--      leaving NULL keeps the fixture KB-scale and the export query ignores SERIEDATA).

CREATE TABLE "USER"."TOURDATA" (
    "TOURID" BIGINT NOT NULL,
    "STARTYEAR" SMALLINT NOT NULL,
    "STARTMONTH" SMALLINT NOT NULL,
    "STARTDAY" SMALLINT NOT NULL,
    "STARTHOUR" SMALLINT NOT NULL,
    "STARTMINUTE" SMALLINT NOT NULL,
    "STARTWEEK" SMALLINT NOT NULL,
    "STARTDISTANCE" INTEGER NOT NULL,
    "DISTANCE" INTEGER NOT NULL,
    "STARTALTITUDE" SMALLINT NOT NULL,
    "STARTPULSE" SMALLINT NOT NULL,
    "DPTOLERANCE" SMALLINT NOT NULL,
    "TOURDISTANCE" INTEGER NOT NULL,
    "TOURALTUP" INTEGER NOT NULL,
    "TOURALTDOWN" INTEGER NOT NULL,
    "DEVICETOURTYPE" VARCHAR(2),
    "DEVICETRAVELTIME" BIGINT NOT NULL,
    "DEVICEDISTANCE" INTEGER NOT NULL,
    "DEVICEWHEEL" INTEGER NOT NULL,
    "DEVICEWEIGHT" INTEGER NOT NULL,
    "DEVICETOTALUP" INTEGER NOT NULL,
    "DEVICETOTALDOWN" INTEGER NOT NULL,
    "DEVICEPLUGINID" VARCHAR(255),
    "DEVICEMODE" SMALLINT,
    "DEVICETIMEINTERVAL" SMALLINT,
    "MAXSPEED" DOUBLE,
    "TOURTITLE" VARCHAR(255),
    "TOURDESCRIPTION" VARCHAR(4096),
    "TOURSTARTPLACE" VARCHAR(4096),
    "TOURENDPLACE" VARCHAR(4096),
    "CALORIES" INTEGER,
    "BODYWEIGHT" DOUBLE,
    "TOURBIKE_BIKEID" BIGINT,
    "DEVICEPLUGINNAME" VARCHAR(255),
    "DEVICEMODENAME" VARCHAR(255),
    "TOURTYPE_TYPEID" BIGINT,
    "TOURPERSON_PERSONID" BIGINT,
    "TOURIMPORTFILEPATH" VARCHAR(255),
    "MERGESOURCETOURID" BIGINT,
    "MERGETARGETTOURID" BIGINT,
    "MERGEDTOURTIMEOFFSET" INTEGER DEFAULT 0,
    "MERGEDALTITUDEOFFSET" INTEGER DEFAULT 0,
    "STARTSECOND" SMALLINT DEFAULT 0,
    "WEATHER_WIND_DIRECTION" INTEGER DEFAULT 0,
    "WEATHER_WIND_SPEED" INTEGER DEFAULT 0,
    "WEATHER_CLOUDS" VARCHAR(255),
    "RESTPULSE" INTEGER DEFAULT 0,
    "ISDISTANCEFROMSENSOR" SMALLINT DEFAULT 0,
    "SERIEDATA" BLOB(2147483647),
    "STARTWEEKYEAR" SMALLINT DEFAULT 1977,
    "DATETIMECREATED" BIGINT DEFAULT 0,
    "DATETIMEMODIFIED" BIGINT DEFAULT 0,
    "ISPULSESENSORPRESENT" INTEGER DEFAULT 0,
    "ISPOWERSENSORPRESENT" INTEGER DEFAULT 0,
    "DEVICEAVGSPEED" DOUBLE DEFAULT 0,
    "DEVICEFIRMWAREVERSION" VARCHAR(255),
    "TEMPERATURESCALE" INTEGER DEFAULT 1,
    "WEATHER" VARCHAR(32000),
    "CONCONIDEFLECTION" INTEGER DEFAULT 0,
    "HRZONE0" INTEGER DEFAULT -1,
    "HRZONE1" INTEGER DEFAULT -1,
    "HRZONE2" INTEGER DEFAULT -1,
    "HRZONE3" INTEGER DEFAULT -1,
    "HRZONE4" INTEGER DEFAULT -1,
    "HRZONE5" INTEGER DEFAULT -1,
    "HRZONE6" INTEGER DEFAULT -1,
    "HRZONE7" INTEGER DEFAULT -1,
    "HRZONE8" INTEGER DEFAULT -1,
    "HRZONE9" INTEGER DEFAULT -1,
    "NUMBEROFHRZONES" INTEGER DEFAULT 0,
    "MAXALTITUDE" DOUBLE DEFAULT 0,
    "MAXPULSE" DOUBLE DEFAULT 0,
    "AVGPULSE" DOUBLE DEFAULT 0,
    "AVGCADENCE" DOUBLE DEFAULT 0,
    "WEATHER_TEMPERATURE_AVERAGE_DEVICE" DOUBLE DEFAULT 0,
    "TOURSTARTTIME" BIGINT DEFAULT 0,
    "TOURENDTIME" BIGINT DEFAULT 0,
    "TOURDEVICETIME_ELAPSED" BIGINT DEFAULT 0,
    "TOURCOMPUTEDTIME_MOVING" BIGINT DEFAULT 0,
    "NUMBEROFTIMESLICES" INTEGER DEFAULT 0,
    "NUMBEROFPHOTOS" INTEGER DEFAULT 0,
    "PHOTOTIMEADJUSTMENT" INTEGER DEFAULT 0,
    "FRONTSHIFTCOUNT" INTEGER DEFAULT 0,
    "REARSHIFTCOUNT" INTEGER DEFAULT 0,
    "TOURIMPORTFILENAME" VARCHAR(255),
    "POWER_AVG" DOUBLE DEFAULT 0,
    "POWER_MAX" INTEGER DEFAULT 0,
    "POWER_NORMALIZED" INTEGER DEFAULT 0,
    "POWER_FTP" INTEGER DEFAULT 0,
    "POWER_TOTALWORK" BIGINT DEFAULT 0,
    "POWER_TRAININGSTRESSSCORE" DOUBLE DEFAULT 0,
    "POWER_INTENSITYFACTOR" DOUBLE DEFAULT 0,
    "POWER_PEDALLEFTRIGHTBALANCE" INTEGER DEFAULT 0,
    "POWER_AVGLEFTTORQUEEFFECTIVENESS" DOUBLE DEFAULT 0,
    "POWER_AVGRIGHTTORQUEEFFECTIVENESS" DOUBLE DEFAULT 0,
    "POWER_AVGLEFTPEDALSMOOTHNESS" DOUBLE DEFAULT 0,
    "POWER_AVGRIGHTPEDALSMOOTHNESS" DOUBLE DEFAULT 0,
    "CADENCEMULTIPLIER" DOUBLE DEFAULT 1.0,
    "ISSTRIDESENSORPRESENT" INTEGER DEFAULT 0,
    "TIMEZONEID" VARCHAR(255),
    "RUNDYN_STANCETIME_MIN" SMALLINT DEFAULT 0,
    "RUNDYN_STANCETIME_MAX" SMALLINT DEFAULT 0,
    "RUNDYN_STANCETIME_AVG" DOUBLE DEFAULT 0,
    "RUNDYN_STANCETIMEBALANCE_MIN" SMALLINT DEFAULT 0,
    "RUNDYN_STANCETIMEBALANCE_MAX" SMALLINT DEFAULT 0,
    "RUNDYN_STANCETIMEBALANCE_AVG" DOUBLE DEFAULT 0,
    "RUNDYN_STEPLENGTH_MIN" SMALLINT DEFAULT 0,
    "RUNDYN_STEPLENGTH_MAX" SMALLINT DEFAULT 0,
    "RUNDYN_STEPLENGTH_AVG" DOUBLE DEFAULT 0,
    "RUNDYN_VERTICALOSCILLATION_MIN" SMALLINT DEFAULT 0,
    "RUNDYN_VERTICALOSCILLATION_MAX" SMALLINT DEFAULT 0,
    "RUNDYN_VERTICALOSCILLATION_AVG" DOUBLE DEFAULT 0,
    "RUNDYN_VERTICALRATIO_MIN" SMALLINT DEFAULT 0,
    "RUNDYN_VERTICALRATIO_MAX" SMALLINT DEFAULT 0,
    "RUNDYN_VERTICALRATIO_AVG" DOUBLE DEFAULT 0,
    "SURFING_NUMBEROFEVENTS" SMALLINT DEFAULT 0,
    "SURFING_MINDISTANCE" SMALLINT DEFAULT -1,
    "SURFING_MINSPEED_STARTSTOP" SMALLINT DEFAULT -1,
    "SURFING_MINSPEED_SURFING" SMALLINT DEFAULT -1,
    "SURFING_ISMINDISTANCE" BOOLEAN DEFAULT false,
    "SURFING_MINTIMEDURATION" SMALLINT DEFAULT -1,
    "HASGEODATA" BOOLEAN DEFAULT false,
    "TRAINING_TRAININGEFFECT_AEROB" DOUBLE DEFAULT 0,
    "TRAINING_TRAININGEFFECT_ANAEROB" DOUBLE DEFAULT 0,
    "TRAINING_TRAININGPERFORMANCE" DOUBLE DEFAULT 0,
    "ISWEATHERDATAFROMPROVIDER" BOOLEAN DEFAULT false,
    "WEATHER_HUMIDITY" SMALLINT DEFAULT 0,
    "WEATHER_PRECIPITATION" DOUBLE DEFAULT 0,
    "WEATHER_PRESSURE" DOUBLE DEFAULT 0,
    "WEATHER_TEMPERATURE_MIN_DEVICE" DOUBLE DEFAULT 0,
    "WEATHER_TEMPERATURE_MAX_DEVICE" DOUBLE DEFAULT 0,
    "WEATHER_TEMPERATURE_WINDCHILL" DOUBLE DEFAULT 0,
    "POWER_DATASOURCE" VARCHAR(255),
    "CADENCEZONE_SLOWTIME" INTEGER DEFAULT 0,
    "CADENCEZONE_FASTTIME" INTEGER DEFAULT 0,
    "CADENCEZONES_DELIMITERVALUE" INTEGER DEFAULT 0,
    "AVGALTITUDECHANGE" INTEGER DEFAULT 0,
    "MAXPACE" DOUBLE DEFAULT 0,
    "TOURDEVICETIME_RECORDED" BIGINT DEFAULT 0,
    "TOURDEVICETIME_PAUSED" BIGINT DEFAULT 0,
    "BODYFAT" DOUBLE DEFAULT 0,
    "BATTERY_PERCENTAGE_START" SMALLINT DEFAULT -1,
    "BATTERY_PERCENTAGE_END" SMALLINT DEFAULT -1,
    "WEATHER_TEMPERATURE_AVERAGE" DOUBLE DEFAULT 0,
    "WEATHER_TEMPERATURE_MAX" DOUBLE DEFAULT 0,
    "WEATHER_TEMPERATURE_MIN" DOUBLE DEFAULT 0,
    "WEATHER_SNOWFALL" DOUBLE DEFAULT 0,
    "WEATHER_AIRQUALITY" VARCHAR(255),
    "TOURLOCATIONSTART_LOCATIONID" BIGINT,
    "TOURLOCATIONEND_LOCATIONID" BIGINT,
    "POOLLENGTH" INTEGER DEFAULT 0,
    "NUMBEROFPASSEDVEHICLES" SMALLINT DEFAULT 0
);

CREATE TABLE "USER"."DBVERSION" ("VERSION" INTEGER NOT NULL);

CREATE TABLE "USER"."TOURTAG" (
    "TAGID" BIGINT NOT NULL,
    "ISROOT" INTEGER,
    "EXPANDTYPE" INTEGER,
    "NAME" VARCHAR(255),
    "NOTES" VARCHAR(32000),
    "IMAGEFILEPATH" VARCHAR(260)
);

CREATE TABLE "USER"."TOURDATA_TOURTAG" (
    "TOURTAG_TAGID" BIGINT NOT NULL,
    "TOURDATA_TOURID" BIGINT NOT NULL
);

CREATE INDEX "USER"."TOURTAG_TAGID" ON "USER"."TOURDATA_TOURTAG" ("TOURTAG_TAGID");
CREATE INDEX "USER"."TOURDATA__TOURLOCATIONEND_LOCATIONID" ON "USER"."TOURDATA" ("TOURLOCATIONEND_LOCATIONID");
CREATE INDEX "USER"."TOURDATA__TOURLOCATIONSTART_LOCATIONID" ON "USER"."TOURDATA" ("TOURLOCATIONSTART_LOCATIONID");
CREATE INDEX "USER"."TOURDATA__BATTERY_PERCENTAGE_START" ON "USER"."TOURDATA" ("BATTERY_PERCENTAGE_START");
CREATE INDEX "USER"."HASGEODATA" ON "USER"."TOURDATA" ("HASGEODATA");
CREATE INDEX "USER"."STARTWEEKYEAR" ON "USER"."TOURDATA" ("STARTWEEKYEAR");
CREATE INDEX "USER"."STARTWEEK" ON "USER"."TOURDATA" ("STARTWEEK");
CREATE INDEX "USER"."TOURIMPORTFILENAME" ON "USER"."TOURDATA" ("TOURIMPORTFILENAME");
CREATE INDEX "USER"."TOURENDTIME" ON "USER"."TOURDATA" ("TOURENDTIME");
CREATE INDEX "USER"."TOURSTARTTIME" ON "USER"."TOURDATA" ("TOURSTARTTIME");
CREATE INDEX "USER"."TOURPERSON" ON "USER"."TOURDATA" ("TOURPERSON_PERSONID");
CREATE INDEX "USER"."TOURTYPE" ON "USER"."TOURDATA" ("TOURTYPE_TYPEID");
CREATE INDEX "USER"."YEARMONTH" ON "USER"."TOURDATA" ("STARTYEAR", "STARTMONTH");

ALTER TABLE "USER"."TOURTAG" ADD CONSTRAINT "TOURTAG_PK" PRIMARY KEY ("TAGID");
ALTER TABLE "USER"."TOURDATA" ADD CONSTRAINT "TOURDATA_PK" PRIMARY KEY ("TOURID");
ALTER TABLE "USER"."TOURDATA_TOURTAG" ADD CONSTRAINT "FK_TOURDATA_TOURTAG_TOURDATA_TOURID"
    FOREIGN KEY ("TOURDATA_TOURID") REFERENCES "USER"."TOURDATA" ("TOURID")
    ON DELETE NO ACTION ON UPDATE NO ACTION;
