###
// @no-log
GET http://{{host}}:{{port}}/api/auth/status
Content-Type: application/json

###
// @no-log
POST http://{{host}}:{{port}}/api/auth/unlock
Content-Type: application/json

{
  "pin": "123456"
}
> {%
    client.test("Response content-type is json", function() {
        let type = response.contentType.mimeType;
        client.assert(type === "application/json", "Expected 'application/json' but received '" + type + "'");
    });
if(response.contentType.mimeType == "application/json") {
    client.global.set("unlockToken", response.body.token);
} else {
    client.global.set("unlockToken", "unknown");
}
%}
