###
// @no-log
GET http://{{host}}:{{port}}/api/parts
Content-Type: application/json

###
// @no-log
POST http://{{host}}:{{port}}/api/parts
Content-Type: application/json

{
  "name": "Campagnolo AFS 03 Bremsscheibe 160mm original vorn"
}
> {%
    client.test("Response content-type is json", function() {
        let type = response.contentType.mimeType;
        client.assert(type === "application/json", "Expected 'application/json' but received '" + type + "'");
    });
if(response.contentType.mimeType == "application/json") {
    // let text = '{ "id": "aaa"}'
    // let arr = JSON.parse(response.body);
    // let arr = JSON.parse(text);
    // client.global.set("partId", arr.id);
    client.global.set("partId", response.body.id);
} else {
    client.global.set("partId", "unknown");
}
%}

###
POST http://localhost:8080/api/partTypes
Content-Type: application/json

{
  "name": "Bremsscheibe vorn"
}

> {%
    client.test("Response content-type is json", function() {
        let type = response.contentType.mimeType;
        client.assert(type === "application/json", "Expected 'application/json' but received '" + type + "'");
    });
    if(response.contentType.mimeType == "application/json") {
        client.global.set("partTypeId", response.body.id);
    } else {
        client.global.set("partTypeId", "unknown");
    }
%}

###
# 62cd2b7c-4766-4962-a2ce-f777d164ab1b
POST http://{{host}}:{{port}}/api/partTypes/{{partTypeId}}/action/relate/{{bikeId}}
#POST http://{{host}}:{{port}}/api/partTypes/{{partTypeId}}/action/relate/4598aded-4886-496c-9042-0358c7f5de7a
Content-Type: application/json

###
// @no-log
GET http://{{host}}:{{port}}/api/partTypes
Content-Type: application/json

###
POST http://{{host}}:{{port}}/api/parts/{{partId}}/action/relate
Content-Type: application/json

{
  "partId": "{{partId}}",
  "partTypeId": "{{partTypeId}}",
  "validFrom": "2022-09-14T14:00:00Z"
}
