openapi: 3.0.3
info:
  title: Cycling Equipment API
  description: The API documentation for tracking cycling equipment and parts - tour related definitions
  version: 1.0.0
  license:
    name: (c) CyclingSir
  contact:
    name: CyclingSir
    url: https://github.com/cyc1ingsir
servers:
  - url: http://localhost:8080/{basePath}
    description: the default server url
    variables:
      basePath:
        default: api
tags:
  - name: Tours
    description: Tour related definitions

paths:
  /tours:
    get:
      operationId: getTours
      description: returns all unfiltered tours
      tags:
        - Tours
      responses:
        '200':
          description: o.k.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tours'
        '204':
          description: No Content
        '400':
          description: Bad Request
        '404':
          description: Not Found
    post:
      operationId: createTour
      description: creates a new tour
      tags:
        - Tours
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Tour'
      responses:
        '200':
          description: o.k.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tour'
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
  /tours/{tourId}:
    parameters:
      - $ref: '#/components/parameters/tourId'
    get:
      operationId: getTour
      description: returns a single tour
      tags:
        - Tours
      responses:
        '200':
          description: o.k.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tour'
        '400':
          description: Bad Request
        '404':
          description: Not Found

components:
  parameters:
    tourId:
      name: tourId
      in: path
      required: true
      schema:
        type: string
        format: uuid
  schemas:
    Tour:
      type: object
      required:
       - title
       - length
       - duration
       - startedAt
      properties:
        id:
          type: string
          format: uuid
          description: id of the created tour
          readOnly: true
        title:
          type: string
          description: tour's model name
        length:
          type: integer
          minimum: 0
        duration:
          type: integer
          format: int64
          minimum: 0
        startedAt:
          type: string
          format: date-time
        bike:
          $ref: './bike-api.yaml#/components/schemas/Bike'
        createdAt:
          type: string
          format: date-time
    Tours:
      type: array
      items:
        $ref: '#/components/schemas/Tour'
