name: Publish to GH Container Registry

on:
  release:
    types: [created]

jobs:

  publish-ghcr:

    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run Gradle Wrapper
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: wrapper
          arguments: |
            dockerPush
            -x test
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
